use_default_settings:
  engines:
    keep_only:
      - google
      - brave
      - bing
      - duckduckgo

search:
  formats:
    - html
    - json

server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277' # Is overwritten by ${SEARXNG_SECRET}